feat: use stylelint
japan-d2/js-cra-template pull request #7
Opened 2020-03-03 11:12 UTC by tatat

resolves #6

2020-03-03 13:21 UTC, kkosuge commented
`eslint src/**/*.ts` じゃくて `eslint src/ --ext .ts,.tsx` でいいんだ~

2020-03-03 13:26 UTC, kkosuge commented
```css
.app-form-item {
  position: relative;

  .app-form-item + .app-form-item {
    margin-top: 1rem;
  }
```
これって、こういうものなの？

2020-03-04 12:04 UTC, uneco requested changes

2020-03-04 12:04 UTC, uneco commented on template/src/App.scss
> +
ここ

2020-03-04 12:04 UTC, tatat commented on template/src/App.scss
> +
ﾎﾝﾄﾀﾞ!

2020-03-04 12:32 UTC, merged